### ISSUE TITLE
About accuracy

### ISSUE THREAD

**Issue by yuzhenglin** [dms-net/scatteringGCN#1]
Hi, I just download the code, and then run it.
`python train.py`
But its accuracy is 81.6. It is lower than your paper(83.6). Could you tell me how to improve it?

**Comment by yimengmin** [comment]
Hi yuzhenglin
Thanks for your interest in our work! the repo is not the final version for the Neurips conference now.
For your question:
Can you please clone the lastest code(where we add random seed for the reproducibility) and run the (one of)following cmd, and check the performance(under smooth==0.3)?
python train.py --hid1 15 --hid2 40 --l1 0.05 --sct_inx1 1 --sct_inx2 3  --smoo 0.3
python train.py --hid1 17 --hid2 38 --l1 0.05 --sct_inx1 1 --sct_inx2 3  --smoo 0.3
python train.py --hid1 18 --hid2 37 --l1 0.05 --sct_inx1 1 --sct_inx2 3  --smoo 0.3
python train.py --hid1 26 --hid2 29 --l1 0.05 --sct_inx1 1 --sct_inx2 3  --smoo 0.3
python train.py --hid1 32 --hid2 23 --l1 0.05 --sct_inx1 1 --sct_inx2 3  --smoo 0.3
python train.py --hid1 34 --hid2 21 --l1 0.05 --sct_inx1 1 --sct_inx2 3  --smoo 0.3
python train.py --hid1 36 --hid2 19 --l1 0.05 --sct_inx1 1 --sct_inx2 3  --smoo 0.3

Note here the scattering GCN's performance relies on the handcrafted design of the width of our channel, for a new attention-based architecture, you can check https://arxiv.org/abs/2010.15010. 
Thanks for your comment, let me know if you have any questions.
YM

**Comment by yuzhenglin** [comment]
Thanks for your reply.
